// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1, arg2) {
  return window['go']['main']['App']['AddRepository'](arg1, arg2);
}

export function DeleteJiraCredentials() {
  return window['go']['main']['App']['DeleteJiraCredentials']();
}

export function DeleteRepository(arg1) {
  return window['go']['main']['App']['DeleteRepository'](arg1);
}

export function GetJiraCredentials() {
  return window['go']['main']['App']['GetJiraCredentials']();
}

export function GetJiraProfile() {
  return window['go']['main']['App']['GetJiraProfile']();
}

export function GetJiraProjectAvatar(arg1) {
  return window['go']['main']['App']['GetJiraProjectAvatar'](arg1);
}

export function GetJiraProjects() {
  return window['go']['main']['App']['GetJiraProjects']();
}

export function GetRepositories() {
  return window['go']['main']['App']['GetRepositories']();
}

export function SaveJiraCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveJiraCredentials'](arg1, arg2, arg3);
}

export function UpdateRepositoryJira(arg1, arg2) {
  return window['go']['main']['App']['UpdateRepositoryJira'](arg1, arg2);
}
