// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRepository(arg1:string,arg2:string):Promise<void>;

export function DeleteJiraCredentials():Promise<void>;

export function DeleteRepository(arg1:number):Promise<void>;

export function GetJiraCredentials():Promise<main.JiraCredentials>;

export function GetJiraProfile():Promise<main.JiraProfile>;

export function GetJiraProjectAvatar(arg1:string):Promise<string>;

export function GetJiraProjects():Promise<Array<main.JiraProject>>;

export function GetRepositories():Promise<Array<main.Repository>>;

export function SaveJiraCredentials(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateRepositoryJira(arg1:number,arg2:string):Promise<void>;
